# Generated by Django 4.2.13 on 2024-07-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Назва'),
        ),
    ]
