# Generated by Django 4.2.13 on 2024-07-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image222',
            field=models.ImageField(blank=True, null=True, upload_to='users_images', verbose_name='аватар'),
        ),
    ]
