# Generated by Django 4.2.13 on 2024-07-28 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_image222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image222',
        ),
    ]
