# Generated by Django 4.2.13 on 2024-07-23 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_rename_prise_products_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
    ]
